server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route  #路由的id,没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  #匹配提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/{id} #断言，路径相匹配进行路由
            #- After=2022-02-08T15:22:24.516+08:00[Asia/Shanghai]  #在某个时间点之后匹配，之前不可用
            #- Cookie=username,zzyy # 请求必须携带cookie
        - id: payment_route2  #路由的id,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配提供服务的路由地址
          predicates:
            - Path=/payment/lb #断言，路径相匹配进行路由

eureka:
  client:
    #表示是否向eureka注册自己
    register-with-eureka: true
    #表示是否需要从 eureka-server 抓取已有的注册信息，单节点无所谓，集群必须为true
    fetch-registry: true
    service-url:
      #注册中心地址
      #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    #实例id,显示在Eureka注册中心的名字，默认是ip地址+端口号
    instance-id: Gateway9527
    #访问路径是否显示ip地址
    prefer-ip-address: true