server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false 表示不向eureka注册自己
    register-with-eureka: false
    #false 表示自己就是注册中心，职责就是维护实例，不需要检索服务
    fetch-registry: false
    service-url:
      #设置和 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka

      # 自我保护模式
#  server:
#    # 关闭自我保护机制，保证不可用服务被及时删除
#    enable-self-preservation: false
#    # 如果一定时间内没有发送心跳包，就注销服务
#    eviction-interval-timer-in-ms: 2000
